name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: "npm"

      - name: Install dependencies
        run: npm ci --quiet --no-progress

      - name: Deploy api
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: "packages/api"
